language: node_js
node_js:
  - 10.16.3
before_install:
  - npm i -g npm@6.9.0
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: iaas-frontend-react
  on:
    all_branches: true
